#!/bin/sh
# Build a portable AppImage of MavixDesktop for Linux x86_64.
# Output: dist/Mavix-Desktop-x86_64.AppImage
#
# Flow:
#   1) PyInstaller --onedir build (via a generated AppImage spec that mirrors
#      mavixdesktop.spec but emits a COLLECT bundle instead of single-file EXE).
#   2) Assemble AppDir layout (AppRun, .desktop, icon, usr/bin, usr/share/...).
#   3) Wrap AppDir with appimagetool into a squashfs-backed .AppImage.
#
# Requirements:
#   * Python venv with project deps + pyinstaller + pillow + numpy
#       python -m venv .venv && source .venv/bin/activate
#       pip install -e .
#       pip install pyinstaller pillow numpy
#   * Internet access on first run (appimagetool is downloaded into
#     .build-cache/ from the AppImageKit continuous release).
#   * Debian/Ubuntu also need: sudo apt install -y patchelf binutils
#
# Usage (from MavixDesktop-UI root):
#   ./scripts/build_appimage.sh
#
# Why --onedir (not --onefile)?
#   AppImage is already a squashfs container. Nesting a self-extracting
#   --onefile bundle inside means the runtime unpacks twice (squashfs mount,
#   then PyInstaller's /tmp/_MEIxxxx). --onedir starts noticeably faster and
#   the on-disk size is comparable since squashfs compresses well.

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$PROJECT_ROOT"

ARCH="${ARCH:-x86_64}"
APPIMAGE_NAME="Mavix-Desktop-${ARCH}.AppImage"
CACHE_DIR="$PROJECT_ROOT/.build-cache"
APPIMAGETOOL="$CACHE_DIR/appimagetool-${ARCH}.AppImage"
APPDIR="$PROJECT_ROOT/build/AppDir"
SPEC_FILE="$PROJECT_ROOT/build/mavixdesktop-appimage.spec"

# ---------------------------------------------------------------------------
# 1. Sanity checks
# ---------------------------------------------------------------------------

if ! command -v pyinstaller >/dev/null 2>&1; then
    echo "ERROR: pyinstaller not found. Install with: pip install pyinstaller" >&2
    exit 1
fi

if ! python3 -c 'import PIL, numpy' >/dev/null 2>&1; then
    echo "ERROR: pillow + numpy required for icon generation. Install with: pip install pillow numpy" >&2
    exit 1
fi

mkdir -p "$CACHE_DIR" "$PROJECT_ROOT/dist" "$PROJECT_ROOT/build"

# ---------------------------------------------------------------------------
# 2. Fetch appimagetool if missing
# ---------------------------------------------------------------------------

if [ ! -x "$APPIMAGETOOL" ]; then
    echo "==> Downloading appimagetool into $CACHE_DIR"
    if ! command -v wget >/dev/null 2>&1; then
        echo "ERROR: wget required to fetch appimagetool. Install: sudo apt install wget" >&2
        exit 1
    fi
    wget -q --show-progress \
        "https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-${ARCH}.AppImage" \
        -O "$APPIMAGETOOL"
    chmod +x "$APPIMAGETOOL"
fi

# ---------------------------------------------------------------------------
# 3. Generate AppImage-flavoured PyInstaller spec (--onedir).
#
# We keep mavixdesktop.spec untouched (Windows build uses it as --onefile).
# This generated spec mirrors its collect_all() hidden-imports list but
# emits a COLLECT bundle so files land in dist/mavixdesktop/.
# ---------------------------------------------------------------------------

echo "==> Generating $SPEC_FILE"
cat >"$SPEC_FILE" <<'PYSPEC'
# Auto-generated by scripts/build_appimage.sh — DO NOT EDIT BY HAND.
# Mirrors mavixdesktop.spec but emits a --onedir COLLECT bundle instead
# of a single-file EXE. Used only by the AppImage build pipeline.
import os

from PyInstaller.utils.hooks import collect_all

# PyInstaller 6.x резолвит относительные пути спека от папки самого спека
# (build/), а не от CWD. Спек лежит в build/, поэтому 'src/...' искался бы
# как build/src/... → «script not found». Берём корень проекта из окружения
# (build_appimage.sh экспортирует MAVIX_APPIMAGE_ROOT) и строим абсолютные пути.
_ROOT = os.environ['MAVIX_APPIMAGE_ROOT']

datas = []
binaries = []
hiddenimports = [
    'aiortc',
    'av',
    'cv2',
    'PySide6.QtSvg',
    'PySide6.QtSvgWidgets',
    'pymavlink.dialects.v20.common',
    'pymavlink.dialects.v20.ardupilotmega',
]

for pkg in ('PySide6', 'av', 'aiortc', 'cv2', 'pymavlink'):
    _datas, _binaries, _hidden = collect_all(pkg)
    datas += _datas
    binaries += _binaries
    hiddenimports += _hidden

datas += [(os.path.join(_ROOT, 'src/mavixdesktop/ui/icons'), 'mavixdesktop/ui/icons')]

a = Analysis(
    [os.path.join(_ROOT, 'src/mavixdesktop/__main__.py')],
    pathex=[os.path.join(_ROOT, 'src')],
    binaries=binaries,
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    runtime_hooks=[],
    excludes=[],
)
pyz = PYZ(a.pure)
exe = EXE(
    pyz, a.scripts, [],
    exclude_binaries=True,
    name='mavixdesktop',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name='mavixdesktop',
)
PYSPEC

# ---------------------------------------------------------------------------
# 4. Run PyInstaller (--onedir)
# ---------------------------------------------------------------------------

echo "==> Running PyInstaller (this may take a few minutes)..."
# Спек читает MAVIX_APPIMAGE_ROOT, чтобы пути к исходникам были абсолютными
# (см. комментарий в сгенерированном спеке выше).
export MAVIX_APPIMAGE_ROOT="$PROJECT_ROOT"
pyinstaller "$SPEC_FILE" --clean --noconfirm --distpath "$PROJECT_ROOT/dist" --workpath "$PROJECT_ROOT/build/pyi"

PYI_OUT="$PROJECT_ROOT/dist/mavixdesktop"
if [ ! -d "$PYI_OUT" ] || [ ! -x "$PYI_OUT/mavixdesktop" ]; then
    echo "ERROR: PyInstaller output not found at $PYI_OUT/mavixdesktop" >&2
    exit 1
fi

# ---------------------------------------------------------------------------
# 5. Assemble AppDir layout
# ---------------------------------------------------------------------------

echo "==> Assembling AppDir at $APPDIR"
rm -rf "$APPDIR"
mkdir -p "$APPDIR/usr/bin"
mkdir -p "$APPDIR/usr/share/applications"
mkdir -p "$APPDIR/usr/share/icons/hicolor/256x256/apps"

# Copy PyInstaller onedir bundle into usr/bin/.
# The bundle dir becomes usr/bin/mavixdesktop-bundle/, and we expose the
# entry binary as usr/bin/mavixdesktop via a tiny shim so AppRun's exec is
# straightforward. (Just symlinking 'mavixdesktop' into the bundle wouldn't
# work because PyInstaller's launcher resolves _internal/ relative to argv[0]).
cp -a "$PYI_OUT" "$APPDIR/usr/bin/mavixdesktop-bundle"
ln -sf "mavixdesktop-bundle/mavixdesktop" "$APPDIR/usr/bin/mavixdesktop"

# .desktop file — appimagetool requires one at AppDir root *and* uses it
# to populate metadata. Categories=Network reflects the WebRTC operator role.
cat >"$APPDIR/mavixdesktop.desktop" <<'DESKTOP'
[Desktop Entry]
Type=Application
Name=Mavix Desktop
Comment=Mavix UAV operator client
Exec=mavixdesktop
Icon=mavixdesktop
Categories=Network;
Terminal=false
StartupNotify=true
DESKTOP
cp "$APPDIR/mavixdesktop.desktop" "$APPDIR/usr/share/applications/mavixdesktop.desktop"

# Icon — 256x256 PNG via the existing Pillow generator. Both root-level
# (appimagetool requirement) and hicolor/256x256/apps/ (XDG standard).
echo "==> Generating icon"
python3 "$SCRIPT_DIR/_make_icon.py" --format png --size 256 --output "$APPDIR/mavixdesktop.png"
cp "$APPDIR/mavixdesktop.png" "$APPDIR/usr/share/icons/hicolor/256x256/apps/mavixdesktop.png"

# AppRun — minimal entry shim. resolves its own dir (via readlink -f to
# follow the AppImage's FUSE-mounted symlink) and execs the bundled binary.
cat >"$APPDIR/AppRun" <<'APPRUN'
#!/bin/sh
HERE="$(dirname "$(readlink -f "$0")")"
exec "$HERE/usr/bin/mavixdesktop" "$@"
APPRUN
chmod +x "$APPDIR/AppRun"

# ---------------------------------------------------------------------------
# 6. Pack AppDir → AppImage
# ---------------------------------------------------------------------------

echo "==> Packing AppImage with appimagetool"
OUT="$PROJECT_ROOT/dist/$APPIMAGE_NAME"
rm -f "$OUT"
# ARCH env tells appimagetool what to write in the runtime header and filename.
ARCH="$ARCH" "$APPIMAGETOOL" "$APPDIR" "$OUT"

if [ ! -f "$OUT" ]; then
    echo "ERROR: appimagetool did not produce $OUT" >&2
    exit 1
fi

chmod +x "$OUT"

echo
echo "Build done: $OUT ($(du -h "$OUT" | cut -f1))"
echo
echo "Copy to MavixWeb static downloads:"
echo "    cp \"$OUT\" ../MavixWeb/public/downloads/mavix-desktop-linux.AppImage"
